// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgC85B1unrCw8E5C39tQTTxWhQVWYZETs',
    appId: '1:216440924868:web:b2a20bf2efcece1a1a7791',
    messagingSenderId: '216440924868',
    projectId: 'apptaxicontrol',
    authDomain: 'apptaxicontrol.firebaseapp.com',
    storageBucket: 'apptaxicontrol.appspot.com',
    measurementId: 'G-YMLM024M9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2K1oSD4BLmyoLURHpeGimOhYNVAGNFE',
    appId: '1:216440924868:android:74997f409f484e191a7791',
    messagingSenderId: '216440924868',
    projectId: 'apptaxicontrol',
    storageBucket: 'apptaxicontrol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7h5EB7y7fYJ3sQTNoPhW4iO3KoWBnJU',
    appId: '1:216440924868:ios:3e839eb2f1d19bb21a7791',
    messagingSenderId: '216440924868',
    projectId: 'apptaxicontrol',
    storageBucket: 'apptaxicontrol.appspot.com',
    iosBundleId: 'com.example.taxiServicios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7h5EB7y7fYJ3sQTNoPhW4iO3KoWBnJU',
    appId: '1:216440924868:ios:3e839eb2f1d19bb21a7791',
    messagingSenderId: '216440924868',
    projectId: 'apptaxicontrol',
    storageBucket: 'apptaxicontrol.appspot.com',
    iosBundleId: 'com.example.taxiServicios',
  );
}
